src/Entity/Content.php
<?php

namespace App\Entity;

use App\Repository\ContentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContentRepository::class)
 */
class Content
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $full_description;

    /**
     * @ORM\ManyToOne(targetEntity=Type::class, inversedBy="contents")
     * @ORM\JoinColumn(nullable=true)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=Content::class, inversedBy="childs")
     */
    private $content;

    /**
     * @ORM\OneToMany(targetEntity=Content::class, mappedBy="content")
     */
    private $childs;

    public function __construct()
    {
        $this->childs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getTitle1(): ?string
    {
        return $this->title1;
    }

    public function setTitle1(string $title1): self
    {
        $this->title1 = $title1;

        return $this;
    }

    public function getTitle2(): ?string
    {
        return $this->title2;
    }

    public function setTitle2(?string $title2): self
    {
        $this->title2 = $title2;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFullDescription(): ?string
    {
        return $this->full_description;
    }

    public function setFullDescription(?string $full_description): self
    {
        $this->full_description = $full_description;

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getContent(): ?self
    {
        return $this->content;
    }

    public function setContent(?self $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getChilds(): Collection
    {
        return $this->childs;
    }

    public function addChild(self $child): self
    {
        if (!$this->childs->contains($child)) {
            $this->childs[] = $child;
            $child->setContent($this);
        }

        return $this;
    }

    public function removeChild(self $child): self
    {
        if ($this->childs->contains($child)) {
            $this->childs->removeElement($child);
            // set the owning side to null (unless already changed)
            if ($child->getContent() === $this) {
                $child->setContent(null);
            }
        }

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Type;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Entity\Content;
use App\Form\ContentType;
use App\Service\UploadFileService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Serializer\Normalizer\AbstractNormalizer;

class DashboardController extends AbstractController
{
    private $encoders;
    private $normalizers;
    private $serializer;
    public function __construct()
    {
        $this->encoders = [new JsonEncoder()];
        $defaultContext = [
            AbstractNormalizer::CIRCULAR_REFERENCE_HANDLER => function ($object, $format, $context) {
                return $object;
            },
        ];
        $this->normalizers = [new ObjectNormalizer(null, null, null, null, null, null, $defaultContext)];
        $this->serializer = new Serializer($this->normalizers, $this->encoders);
    }
    /**
     * @Route("/", name="dashboard", options={"expose"=true})
     */
    public function index()
    {
        return $this->render('dashboard/index.html.twig');
    }

    /**
     * @Route("/find/all/type", name="type.findAll", options={"expose"=true})
     */
    public function findAllType()
    {
        $em = $this->getDoctrine()->getManager();
        $allTypes = $em->getRepository(Type::class)->findAll();
        $allTypesJson = $this->serializer->serialize($allTypes, 'json', ['groups' => ['normal']]);
        return JsonResponse::fromJsonString($allTypesJson);
    }

    /**
     * @Route("/find/all/by/type/{type}", name="type.findAllByType", options={"expose"=true})
     */
    public function getContentByType(Type $type)
    {
        $em = $this->getDoctrine()->getManager();
        $allContentsByType = $em->getRepository(Type::class)->find($type);
        $allContentJson = $this->serializer->serialize($allContentsByType, 'json', ['groups' => ['normal']]);
        return JsonResponse::fromJsonString($allContentJson);
    }

    /**
     * @Route("/delete/content/{content}", name="content.remove", options={"expose"=true})
     */
    public function deleteContentById(Content $content)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($content);
        $em->flush();
        return $this->json(['status' => 'ok']);
    }

    /**
     * @Route("/edit/content/{content}", name="content.edit", options={"expose"=true})
     */
    public function editContent(Content $content)
    {
        $form = $this->createForm(ContentType::class, $content);
        return $this->render('dashboard/edit.html.twig', [
            'form' => $form->createView(),
            'content' => $content
        ]);
    }

    /**
     * @Route("/add/content/{id}", name="content.add", options={"expose"=true})
     */
    public function addContent($id)
    {
        $content = new Content();
        $form = $this->createForm(ContentType::class, $content);
        return $this->render('dashboard/add.html.twig', [
            'form' => $form->createView(),
            'idContent' => $id
        ]);
    }

    /**
     * @Route("/valide/edit/content/{content}", name="content.valid", options={"expose"=true})
     */
    public function valideContent(Request $request, Content $content, UploadFileService $uploadFileService)
    {
        $form = $this->createForm(ContentType::class, $content);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $fileData = $form->get('img')->getData();
            $path = $this->getParameter('file_upload_dir');
            $newFileName = $uploadFileService->doUpload($fileData, $path);
            if ($newFileName) {
                $content->setImg($newFileName);
            }
            $em = $this->getDoctrine()->getManager();
            $em->persist($content);
            $em->flush();
        }
        $allContentJson = $this->serializer->serialize($content, 'json', ['groups' => ['normal']]);
        return JsonResponse::fromJsonString($allContentJson);
    }

    /**
     * @Route("/valide/new/content/{content}", name="content.validNew", options={"expose"=true})
     */
    public function valideAddContent(Request $request,Content $content, UploadFileService $uploadFileService)
    {
        $lastContent = $content;
        $content = new Content();
        $form = $this->createForm(ContentType::class, $content);
        $form->handleRequest($request);
        if ($form->isValid()) {
            $fileData = $form->get('img')->getData();
            $path = $this->getParameter('file_upload_dir');
            $newFileName = $uploadFileService->doUpload($fileData, $path);
            if ($newFileName) {
                $content->setImg($newFileName);
            }
            $content->setContent($lastContent);
            $em = $this->getDoctrine()->getManager();
            $em->persist($content);
            $em->flush();
        }
        $allContentJson = $this->serializer->serialize($content, 'json', ['groups' => ['normal']]);
        return JsonResponse::fromJsonString($allContentJson);
    }

    /**
     * @Route("/api/get/content/", name="content.get", options={"expose"=true})
     */
    public function getContentApi()
    {
        $em = $this->getDoctrine()->getManager();
        $types = $em->getRepository(Type::class)->findAll();
        $types = $this->serializer->normalize($types);
        $data = [];
        foreach ($types as $keyType => $type) {
            $data[$type['name']] = $this->removeUnUsedIndex('type', $type['contents']);
            $data[$type['name']]  = $this->getChild($data[$type['name']]);
        }
        $dataJson = $this->serializer->serialize($data, 'json', ['groups' => ['normal']]);
        return JsonResponse::fromJsonString($dataJson);
    }

    private function removeUnUsedIndex($index, $array)
    {
        foreach ($array as $key => $value) {
            unset($array[$key][$index]);
            unset($array[$key]['content']);
        }
        return $array;
    }

    private function removeUnUsedIndexChild($index, $array)
    {
        foreach ($array as $key => $value) {
            unset($array[$key][$index]);
            unset($array[$key]['content']);
            unset($array[$key]['childs']);
        }
        return $array;
    }

    private function getChild($data)
    {
        foreach ($data as $key => $value) {
            if (count($value['childs'])) {
                $arrayData = $this->serializer->normalize($value['childs']);
                $data[$key]['childs'] = $this->removeUnUsedIndexChild('type', $arrayData);
            }
        }
        return $data;
    }
}

templates/dashboard/add.html.twig
<div class="dialog-content">
	<div class="dialog-header">
		<h3 class="text-center h1-custom-style">Modifier un contenu</h3>
	</div>
	<input type="hidden" value="{{idContent}}" id="id_content"></input>
	<div class="container" style="width: 650px !important;">
		{{ form_start(form,{attr : {id:'form_content'}}) }}
		<div class="form-group bmd-form-group is-filled">
			{{ form_label(form.title1,'Titre numero 1',{attr:{class:'bmd-label-floating'}}) }}
			{{ form_widget(form.title1,{attr:{class:'form-control'}}) }}
		</div>
		<div class="form-group bmd-form-group is-filled">
			{{ form_label(form.title2,'Titre numero 2',{attr:{class:'bmd-label-floating'}}) }}
			{{ form_widget(form.title2,{attr:{class:'form-control'}}) }}
		</div>
		<div class="form-group bmd-form-group is-filled">
			{{ form_label(form.img,'Image',{attr:{class:'bmd-label-floating'}}) }}
			{{ form_widget(form.img,{attr:{class:'form-control'}}) }}
		</div>
		<div class="form-group bmd-form-group is-filled">
			{{ form_label(form.description,'Descriptionns 1',{attr:{class:'bmd-label-floating'}}) }}
			{{ form_widget(form.description,{attr:{class:'form-control'}}) }}
		</div>
		<div class="form-group bmd-form-group is-filled">
			{{ form_label(form.description,'Descriptionns 2',{attr:{class:'bmd-label-floating'}}) }}
			{{ form_widget(form.full_description,{attr:{class:'form-control'}}) }}
		</div>
		{{ form_end(form) }}
		<button class="btn btn-success pull-right" onclick="clickSave()">
			Enregistrer
		</button>
	</div>
</div>
<script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
<script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>
<script>
	function clickSave() {
		$('#form_content').ajaxSubmit(
			{
				url:Routing.generate('content.validNew',{ content : $('#id_content').val()}),
				type:'post'
			}
		)
    }
</script>

templates/dashboard/edit.html.twig
<div class="dialog-content">
	<input type="text" id="content_id" name="content[id]" value="{{content.id}}" hidden>
	<div class="dialog-header">
		<h3 class="text-center h1-custom-style">Modifier un contenu</h3>
	</div>
	<div class="container" style="width: 650px !important;">
		{{ form_start(form,{attr : {id:'form_content'}}) }}
		<div class="form-group bmd-form-group is-filled">
			{{ form_label(form.title1,'Titre numero 1',{attr:{class:'bmd-label-floating'}}) }}
			{{ form_widget(form.title1,{attr:{class:'form-control'}}) }}
		</div>
		<div class="form-group bmd-form-group is-filled">
			{{ form_label(form.title2,'Titre numero 2',{attr:{class:'bmd-label-floating'}}) }}
			{{ form_widget(form.title2,{attr:{class:'form-control'}}) }}
		</div>
		<div class="form-group bmd-form-group is-filled">
			{{ form_label(form.img,'Image',{attr:{class:'bmd-label-floating'}}) }}
			{{ form_widget(form.img,{attr:{class:'form-control'}}) }}
		</div>
		<div class="form-group bmd-form-group is-filled">
			{{ form_label(form.description,'Descriptionns 1',{attr:{class:'bmd-label-floating'}}) }}
			{{ form_widget(form.description,{attr:{class:'form-control'}}) }}
		</div>
		<div class="form-group bmd-form-group is-filled">
			{{ form_label(form.description,'Descriptionns 2',{attr:{class:'bmd-label-floating'}}) }}
			{{ form_widget(form.full_description,{attr:{class:'form-control'}}) }}
		</div>
		{{ form_end(form) }}
		<button class="btn btn-success pull-right" onclick="clickSave()">
			Enregistrer
		</button>
	</div>
</div>
<script src="{{ asset('bundles/fosjsrouting/js/router.min.js') }}"></script>
<script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>
<script>
	function clickSave() {
		$('#form_content').ajaxSubmit(
			{
				url:Routing.generate('content.valid',{
					content:$('#content_id').val()
				}),
				type:'post'
			}
		)
    }
</script>

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
	<div class="content" ng-controller="tableCtrl">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						{% verbatim %}
							<div class="card-header card-header-primary">
								<md-input-container>
									<label>Menu à modifier</label>
									<md-select name="type" ng-model="selected_type" ng-change="changeType()">
										<md-option ng-repeat="type in allTypes" ng-value="type.id">{{type.title}}</md-option>
									</md-select>
								</md-input-container>
							</div>
							<div class="card-body" ng-init="initTable()">
								<table class="table">
									<thead>
										<tr>
											<th>Titre 1</th>
											<th>Titre 2</th>
											<th>Image</th>
											<th>Descriptions</th>
											<th>Descriptions 2</th>
											<th class="text-center">Action</th>
										</tr>
									</thead>
									<tbody>
										<tr ng-repeat="content in contents">
											<td>{{content.title1 | limitTo:20}}</td>
											<td>{{content.title2 | limitTo:20}}</td>
											<td>{{content.img | limitTo:20}}</td>
											<td>{{content.description | limitTo:20}}</td>
											<td>{{content.fullDescription | limitTo:20}}</td>
											<td class="td-actions text-center">
												<button type="button" rel="tooltip" class="btn btn-success" ng-click="showEditDialog($event,$index,'parent')">
													<md-tooltip>Modifier</md-tooltip>
													<i class="material-icons">edit</i>
												</button>
											</td>
										</tr>
									</tbody>
								</table>
								<h3 class="text-center text-info">
									Enfants
								</h3>
								<button class="btn btn-success" ng-click="showAddDialog($event)">Ajouter</button>
								<div ng-if="contents[0].childs.length > 0">
									<table class="table">
										<thead>
											<tr>
												<th>Titre 1</th>
												<th>Titre 2</th>
												<th>Image</th>
												<th>Descriptions</th>
												<th>Descriptions 2</th>
												<th class="text-center">Action</th>
											</tr>
										</thead>
										<tbody>
											<tr ng-repeat="content in contents[0].childs">
												<td>{{content.title1 | limitTo:20}}</td>
												<td>{{content.title2 | limitTo:20}}</td>
												<td>{{content.img | limitTo:20}}</td>
												<td>{{content.description | limitTo:20}}</td>
												<td>{{content.fullDescription | limitTo:20}}</td>
												<td class="td-actions text-center">
													<button type="button" rel="tooltip" class="btn btn-success" ng-click="showEditDialog($event,$index,'child')">
														<md-tooltip>Modifier</md-tooltip>
														<i class="material-icons">edit</i>
													</button>
													<button type="button" rel="tooltip" class="btn btn-danger" ng-click="showConfirm($event,$index)">
														<md-tooltip>Suprimer</md-tooltip>
														<i class="material-icons">close</i>
													</button>
												</td>
											</tr>
										</tbody>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				{% endverbatim %}
			</div>
		</div>
	</div>
</div></div>{% endblock %}